#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# icescrum
URL="https://www.icescrum.com/downloads/v7/icescrum.jar"

dl $URL /usr/local/src

wget -qO - \
    https://packages.adoptium.net/artifactory/api/gpg/key/public | \
    gpg --dearmor > /usr/share/keyrings/adoptium.gpg

apt update
apt install -y temurin-8-jdk temurin-8-jre
