#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# icescrum
VERSION="R6_3"
URL="http://www.icescrum.org/downloads/icescrum_${VERSION}_war.zip"
dl $URL /usr/local/src

# icescrum dep
JAR="geronimo/specs/geronimo-servlet_3.0_spec/1.0/geronimo-servlet_3.0_spec-1.0.jar"
URL="http://repo1.maven.org/maven2/org/apache/$JAR"
dl $URL /usr/share/tomcat6/lib

