#!/bin/sh -ex

DB_NAME=icescrum
DB_USER=icescrum
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBAPPS=/var/lib/tomcat6/webapps
BASE_DIR=/var/local/lib/icescrum

# unpack and drop war into webapps
unzip $SRC/icescrum_*.zip -d $SRC
rm $SRC/icescrum_*.zip

rm -rf $WEBAPPS/ROOT
mv $SRC/icescrum.war $WEBAPPS/ROOT.war

# tweak configuration, set in tomcat environment and create base_dir
CONF=/etc/icescrum/config.properties

sed -i "s|DB_NAME|$DB_NAME|" $CONF
sed -i "s|DB_USER|$DB_USER|" $CONF
sed -i "s|DB_PASS|$DB_PASS|" $CONF
sed -i "s|BASE_DIR|$BASE_DIR|" $CONF

echo "icescrum_config_location=$CONF" >> /etc/default/tomcat6

chown tomcat6:tomcat6 $CONF
chmod 640 $CONF

mkdir -p $BASE_DIR
chown -R tomcat6:tomcat6 $BASE_DIR

# allow binding to 80/443 (and bugfix LP#594989)
echo AUTHBIND=yes >> /etc/default/tomcat6
echo 0.0.0.0/0:1,1023 > /etc/authbind/byuid/106

