#!/bin/sh -ex

DB_NAME=icescrum
DB_USER=icescrum
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBAPPS=/var/lib/tomcat6/webapps
BASE_DIR=/var/local/lib/icescrum

# unpack and drop war into webapps
unzip $SRC/icescrum_*.zip -d $SRC
rm $SRC/icescrum_*.zip

rm -rf $WEBAPPS/ROOT
mv $SRC/icescrum.war $WEBAPPS/ROOT.war

# tweak configuration, set in tomcat environment and create base_dir
CONF=/etc/icescrum/config.groovy

sed -i "s|DB_NAME|$DB_NAME|" $CONF
sed -i "s|DB_USER|$DB_USER|" $CONF
sed -i "s|DB_PASS|$DB_PASS|" $CONF
sed -i "s|BASE_DIR|$BASE_DIR|" $CONF

echo "icescrum_config_location=$CONF" >> /etc/default/tomcat6

chown tomcat6:tomcat6 $CONF
chmod 640 $CONF

mkdir -p $BASE_DIR
chown -R tomcat6:tomcat6 $BASE_DIR

# allow binding to 80/443 (and bugfix LP#594989)
echo AUTHBIND=yes >> /etc/default/tomcat6
echo 0.0.0.0/0:1,1023 > /etc/authbind/byuid/106

# increase memory defaults
echo "JAVA_OPTS=\"\${JAVA_OPTS} -Xmx512M -XX:MaxPermSize=512M\"" >> /etc/default/tomcat6

# modify tomcat connectors protocol required by icescrum
CONF=/etc/tomcat6/server.xml
sed -i "s|HTTP\/1.1|org.apache.coyote.http11.Http11NioProtocol|" $CONF

# update local policy permissions
cat >>/etc/tomcat6/policy.d/50local.policy<<EOF
grant codeBase "file:\${catalina.base}/webapps/ROOT/-" {
    permission java.security.AllPermission;
};
grant {
    permission java.net.SocketPermission "localhost:3306", "connect, resolve";
};
EOF

# workaround icescrum bug
mkdir -p /usr/share/tomcat6/.lbdsl
chown -R tomcat6:tomcat6 /usr/share/tomcat6/.lbdsl

# generate tomcat keystore from default ssl certificate
/usr/lib/inithooks/firstboot.d/16tomcat-sslcert

# setup the database
/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# initialize icescrum
/etc/init.d/tomcat6 start
curl --max-time 1200 'http://localhost/'
/etc/init.d/tomcat6 stop

# set default configuration
/usr/lib/inithooks/bin/icescrum.py --pass=$ADMIN_PASS --email=$ADMIN_MAIL --domain=$DOMAIN

# stop mysql
/etc/init.d/mysql stop

