#!/bin/bash -e
# regenerate icescrum mysql password

. /etc/default/inithooks

CONF=/etc/icescrum/config.groovy
PASSWORD=$(mcookie)
sed -i "s|dataSource.password =.*|dataSource.password = \"$PASSWORD\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=icescrum --pass="$PASSWORD"

